[project]
title = "Health Activity Dashboard"
version = "0.1.0"
port = 8501
slug = "health-activity-dashboard"  
entrypoint = "hello.py"  

[branding]
name = "Health Tracker Insights"
logo = "images/logo.png" 
favicon = "images/favicon.ico"  
primaryColor = "#4CAF50"          # Green tone

[data.health_activity_data]
type = "csv"
path = "data/health_activity_data.csv"  

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
